/**
 * Shared print-concept catalog boundary.
 *
 * The locale registry supplies translations; this stable concept union supplies
 * the typed contract between semantic documents and each locale catalog view.
 */
export const PRINT_CONCEPT_IDS = [
  'print.taxInvoiceTitle',
  'print.invoiceTitle',
  'print.invoiceNumber',
  'print.time',
  'print.customerShort',
  'print.numberShort',
  'print.address',
  'print.call',
  'print.note',
  'print.phoneLong',
  'print.subtotalExclTax',
  'print.serviceChargeShort',
  'print.grandTotal',
  'print.thankYouShort',
  'print.thankYouVisitAgain',
  'print.pleaseComeAgain',
  'print.ratesInclusiveNote',
  'print.pointsEarned',
  'print.pointsBalance',
  'print.pointsRedeemed',
  'print.kot.title',
  'print.kot.banner',
  'print.kot.station',
  'print.kot.type',
  'print.kot.noPendingItems',
  'print.kot.end',
  'print.hsn',
  'print.test.title',
  'print.test.networkUsb',
  'print.test.columns',
  'print.test.wrapHint',
  'print.test.success',
  'receipt.billNumber',
  'receipt.date',
  'pos.tableLabel',
  'pos.customer',
  'receipt.customerNo',
  'receipt.phone',
  'receipt.item',
  'receipt.qty',
  'receipt.rate',
  'receipt.amount',
  'printTest.amt',
  'pos.subtotal',
  'pos.discount',
  'pos.tax',
  'pos.delivery',
  'pos.packaging',
  'receipt.totalTax',
  'receipt.serviceCharge',
  'receipt.taxDetails',
  'receipt.payments',
  'receipt.thankYou',
  'receipt.taxIncluded',
  'receipt.reprint',
  'receipt.onlineOrder',
  'pos.orderNumber',
  'pos.orderTypeDineIn',
  'pos.orderTypeDelivery',
  'pos.orderTypeOnline',
  'pos.orderTypeTakeaway',
  'pos.methodCash',
  'pos.methodCard',
  'pos.methodWallet',
] as const;

export type PrintConceptId = (typeof PRINT_CONCEPT_IDS)[number];
